
package com.example.calculator.soap.lib;

import javax.jws.WebService;
import javax.xml.ws.BindingType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(portName = "CalculatorSoap", serviceName = "Calculator", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://www.dneonline.com/calculator.asmx?wsdl", endpointInterface = "com.example.calculator.soap.lib.CalculatorSoap")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class Calculator_CalculatorSoapImpl
    implements CalculatorSoap
{


    public Calculator_CalculatorSoapImpl() {
    }

    /**
     * Adds two integers. This is a test WebService. ©DNE Online
     * 
     * @param intB
     * @param intA
     * @return
     *     returns int
     */
    public int add(int intA, int intB) {
        //replace with your impl here
        return 0;
    }

    /**
     * 
     * @param intB
     * @param intA
     * @return
     *     returns int
     */
    public int subtract(int intA, int intB) {
        //replace with your impl here
        return 0;
    }

    /**
     * 
     * @param intB
     * @param intA
     * @return
     *     returns int
     */
    public int multiply(int intA, int intB) {
        //replace with your impl here
        return 0;
    }

    /**
     * 
     * @param intB
     * @param intA
     * @return
     *     returns int
     */
    public int divide(int intA, int intB) {
        //replace with your impl here
        return 0;
    }

}
